//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daenet.DurableTaskMicroservices.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DaenetSystemIntegration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DaenetSystemIntegration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daenet.DurableTaskMicroservices.Common.DaenetSystemIntegration", typeof(DaenetSystemIntegration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to commit transaction rollback after some error in the method RunTask() of the adapter \&quot;{0}\&quot;..
        /// </summary>
        internal static string ErrFailedToCommitTransactionRollback {
            get {
                return ResourceManager.GetString("ErrFailedToCommitTransactionRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileReceiveAdapter Error.
        /// </summary>
        internal static string ErrFileReceiveAdapter {
            get {
                return ResourceManager.GetString("ErrFileReceiveAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestration failed before LoggingContext has been initialized. InstanceId: &apos;{0}&apos; - &apos;{1}&apos;!.
        /// </summary>
        internal static string ErrLoggingSystemFailed {
            get {
                return ResourceManager.GetString("ErrLoggingSystemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation of the orchestration {0} has been failed..
        /// </summary>
        internal static string ErrOrchestrationCompensationFailed {
            get {
                return ResourceManager.GetString("ErrOrchestrationCompensationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestration failed. InstanceId: &apos;{0}&apos; - &apos;{1}&apos;!.
        /// </summary>
        internal static string ErrOrchestrationFailed {
            get {
                return ResourceManager.GetString("ErrOrchestrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An TaskFailed exception occurred during the execution of the orchestration {0}..
        /// </summary>
        internal static string ErrTaskFailedException {
            get {
                return ResourceManager.GetString("ErrTaskFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An validation exception occurred while executing the Task based on the type \&quot;{0}\&quot;.\r\nThe data being validated are represented by the following string: \n\r\&quot;{1}\&quot;.\r\nThe validation results are: {2}.
        /// </summary>
        internal static string ErrValidationRule {
            get {
                return ResourceManager.GetString("ErrValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while executing the RunTask() method of the adapter \&quot;{0}\&quot;. Trying to rollback transaction ....
        /// </summary>
        internal static string ErryAdapterExecution {
            get {
                return ResourceManager.GetString("ErryAdapterExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL Statement {0} defined by CheckDataCmdText has been successfully executed and delivered the value {1} as result..
        /// </summary>
        internal static string InfCheckDataCmdTextResults {
            get {
                return ResourceManager.GetString("InfCheckDataCmdTextResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileReceiveAdapter End. File: {0}.
        /// </summary>
        internal static string InfEndFileReceiveAdapter {
            get {
                return ResourceManager.GetString("InfEndFileReceiveAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL Statement {0} defined by FetchDataCmdText has been successfully executed and delivered {1} as result..
        /// </summary>
        internal static string InfFetchDataCmdTextResults {
            get {
                return ResourceManager.GetString("InfFetchDataCmdTextResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed execution of the method {0}..
        /// </summary>
        internal static string InfMethodCompleted {
            get {
                return ResourceManager.GetString("InfMethodCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starded execution of the methd {0} ....
        /// </summary>
        internal static string InfMethodStarted {
            get {
                return ResourceManager.GetString("InfMethodStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileReceiveAdapter Start. Input FileMask: {0}, Folder: {1}.
        /// </summary>
        internal static string InfStartFileReceiveAdapter {
            get {
                return ResourceManager.GetString("InfStartFileReceiveAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rollback successfully commited..
        /// </summary>
        internal static string InfTransactionRolledBack {
            get {
                return ResourceManager.GetString("InfTransactionRolledBack", resourceCulture);
            }
        }
    }
}
